### ISSUE TITLE
Invalid IP addresses

### ISSUE THREAD

**Issue by mleblebici** [CriticalPathSecurity/Public-Intelligence-Feeds#1]
Hello, 
There are wrong IP addresses like 553.087.738.225, 692.661.75.75 in log4j feeds.

**Comment by jamateov** [comment]
Also you have repat IP addresses: like 45.155.205.233 and 34.214.48.8.
and others with the octect starting with 0 like: 7.59.4.07 or 2.33.66.07 or 02.05.09.09

**Comment by Patrick-Kelley** [comment]
That's correct. I'm working on a solution as I don't have a static path and format, which I typically get from other sources or my own. The path is moving due to two of them being gists and grep out proper regex to make a clean feed is also producing errors. 

I'll see what I can work out today in between "work" work.

**Comment by Patrick-Kelley** [comment]
Alright, I've changed the automation around a bit and so far... it's properly processing the generic feed and zeek-formatted feed. 

Short version: The regex I was using to match the pattern wasn't doing a good enough job. For the moment, I'm sed/awk'ing the addresses out for you all. 

Working on bringing in the other sources, now.
